### PR TITLE
Fix GitLab issues with empty description failing

### LINKED ISSUE #151: Gitlab to Discord: Request failed for issue events
Push events work fine, but issue events are broken.

> Hook executed successfully but returned HTTP 502 {"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n at createError (/workspace/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/workspace/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/workspace/node_modules/axios/lib/adapters/http.js:236:11)\n at IncomingMessage.emit (events.js:322:22)\n at endReadableNT (_stream_readable.js:1187:12)\n at processTicksAndRejections (internal/process/task_queues.js:84:21)","config":{"url":"[original discord webhook URL]","method":"post","data":"{\"embeds\":[{\"title\":\"undefined issue #[number] on [project name]\",\"url\":\"[link to issue]\",\"author\":{\"name\":\"[author name]\",\"icon_url\":\"[author avatar]\"},\"fields\":[{\"name\":\"[issue title]\",\"value\":\"\"}],\"footer\":{\"text\":\"Powered by Skyhook\"},\"color\":16556838}]}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.19.2","Content-Length":379},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}

### PR DESCRIPTION
**Pull request by jameds**
Resolves #151

### CODE REVIEW

File: src/provider/GitLab.ts [hunk 1]
```diff
@@ -105,10 +105,14 @@ class GitLab extends BaseProvider {
         this.embed.title = actions[this.body.object_attributes.action] + ' issue #' + this.body.object_attributes.iid + ' on ' + this.body.project.name
         this.embed.url = this.body.object_attributes.url
         this.embed.author = this.authorFromBody()
-        const field = new EmbedField()
-        field.name = this.body.object_attributes.title
-        field.value = (this.body.object_attributes.description != null && this.body.object_attributes.description.length > 1024) ? this.body.object_attributes.description.substring(0, 1023) + '\u2026' : this.body.object_attributes.description
-        this.embed.fields = [field]
+        if (this.body.object_attributes.description != '') {
```
Comment (dscalzi) [inline src/provider/GitLab.ts:108]: !== for strict equality

File: src/provider/GitLab.ts [hunk 2]
```diff
@@ -105,10 +105,14 @@ class GitLab extends BaseProvider {
...
+            const field = new EmbedField()
+            field.name = this.body.object_attributes.title
+            field.value = (this.body.object_attributes.description.length > 1024) ? this.body.object_attributes.description.substring(0, 1023) + '\u2026' : this.body.object_attributes.description
+            this.embed.fields = [field]
+        } else {
+            this.embed.description = '**' + this.body.object_attributes.title + '**'
```
Comment (dscalzi) [inline src/provider/GitLab.ts:114]: Use a string literal
```
`**${variable}**`
```

**Review by dscalzi — CHANGES_REQUESTED** [review]

**Review by dscalzi — APPROVED** [review]
